### ISSUE TITLE
Find a better way to store the password

### ISSUE THREAD

**Issue by aessing** [aessing/unifi-udm-backup#13]
The FTP password is stored in the script and will be written to the cron.d-file. From a security point of view, the password should be encrypted and stored in a separate file.

- [ ] Investigate a solution
- [ ] Implement a better way to store the FTP password

**Comment by gtrabanco** [comment]
There is a way to do that... You can delete the vars from the script file and add in the on_boot.d script the argument `--env-file=/mnt/data/backup/conf.env` and store in `/mnt/data/backup/conf.env` those vars.
